FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine as build
RUN echo "build" > /build.txt
CMD [ "balena-idle" ]

FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine as prod
COPY --from=build /build.txt /build.txt
RUN echo "prod" > /prod.txt
CMD [ "balena-idle" ]

FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine as dev
COPY --from=build /build.txt /build.txt
RUN echo "dev" > /dev.txt
CMD [ "balena-idle" ]